
# Site settings
title:        rishipuri
description:  This is where rishipuri lives on the Interwebs. He is a web developer currently based in UK

url:          http://rishipuri.co.uk/
baseurl:      ""

permalink:    /blog/:year/:month/:day/:title/


# Build settings
markdown:     kramdown

sass:
  sass_dir:   _sass
  style:      :compressed